/**
 * Simple User Service — the PROVIDER side of the contract.
 *
 * In a real microservice architecture, this would be a separate repo/service.
 * For this portfolio project, we keep both sides together to demonstrate the full flow.
 *
 * The provider verification test will:
 * 1. Start this service
 * 2. Load the pact file generated by the consumer
 * 3. Replay each interaction against this service
 * 4. Verify the responses match what the consumer expects
 *
 * If verification fails → the provider is breaking the consumer's contract.
 */

import http from 'http';

interface User {
    id: number;
    name: string;
    email: string;
}

// In-memory data store (simulates a database)
const users: User[] = [
    { id: 1, name: 'Alice', email: 'alice@example.com' },
    { id: 2, name: 'Bob', email: 'bob@example.com' },
];

let nextId = 3;

export function createServer(port: number = 3001): http.Server {
    const server = http.createServer((req, res) => {
        const url = new URL(req.url || '/', `http://localhost:${port}`);

        // GET /api/users
        if (req.method === 'GET' && url.pathname === '/api/users') {
            res.writeHead(200, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify(users));
            return;
        }

        // GET /api/users/:id
        const userMatch = url.pathname.match(/^\/api\/users\/(\d+)$/);
        if (req.method === 'GET' && userMatch) {
            const userId = parseInt(userMatch[1]);
            const user = users.find(u => u.id === userId);
            if (user) {
                res.writeHead(200, { 'Content-Type': 'application/json' });
                res.end(JSON.stringify(user));
            } else {
                res.writeHead(404, { 'Content-Type': 'application/json' });
                res.end(JSON.stringify({ error: 'User not found' }));
            }
            return;
        }

        // POST /api/users
        if (req.method === 'POST' && url.pathname === '/api/users') {
            let body = '';
            req.on('data', chunk => body += chunk);
            req.on('end', () => {
                const { name, email } = JSON.parse(body);
                const newUser: User = { id: nextId++, name, email };
                users.push(newUser);
                res.writeHead(201, { 'Content-Type': 'application/json' });
                res.end(JSON.stringify(newUser));
            });
            return;
        }

        res.writeHead(404);
        res.end();
    });

    return server;
}

// Start server if run directly
if (require.main === module) {
    const server = createServer(3001);
    server.listen(3001, () => {
        console.log('User Service running on http://localhost:3001');
    });
}
